In [3]:
import numpy

In [4]:
r = numpy.c_[5,12]

In [6]:
r.shape

(1, 2)

In [7]:
r[:1]

array([[ 5, 12]], dtype=int32)

In [8]:
r

array([[ 5, 12]], dtype=int32)

In [9]:
r[:2]

array([[ 5, 12]], dtype=int32)

In [17]:
m = numpy.r_[4,2,3]

In [18]:
m

array([4, 2, 3], dtype=int32)

In [19]:
m.shape

(3,)

In [20]:
m[0]

4

In [21]:
m[1]

2

In [23]:
x = [2,3,4]
y = [6,7,8,9]
z = numpy.r_[x,y]

In [24]:
z

array([2, 3, 4, 6, 7, 8, 9])

In [25]:
z.shape

(7,)

In [26]:
l = [0,9,7]
k = numpy.c_[x,l]
k

array([[2, 0],
       [3, 9],
       [4, 7]])

In [27]:
k.shape

(3, 2)