### K-Nearest Neighbour or (KNN) is one of the simplest Machine Learning algorithms based on Supervised Learning technique.

In [11]:
from sklearn import datasets
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [7]:
iris = datasets.load_iris()

In [8]:
x= iris.data
y= iris.target

In [10]:
x.shape,y.shape

((150, 4), (150,))

In [12]:
knn = KNeighborsClassifier(n_neighbors=1)

In [13]:
knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [14]:
knn.fit(x,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [15]:
knn.predict([4,5,6,2])

ValueError: Expected 2D array, got 1D array instead:
array=[4 5 6 2].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [16]:
import numpy as np

In [22]:
testarray = np.array([4,2,2,2])

In [19]:
testarray.shape

(4,)

In [23]:
knn.predict([testarray])

array([1])

In [24]:
## output shows the type of the flower


In [25]:
testarray = np.array([4,5,6,7])
knn.predict([testarray])

array([2])

In [27]:
testarray = np.array([1,1,1,1])
knn.predict([testarray])

array([0])